/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it3projekt;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lenovo
 */
public class JournalPanel extends javax.swing.JPanel {
    private CardLayout card;
    private JPanel panelHolder;

    public JournalPanel(CardLayout c, JPanel p, Arkiv a) {
        initComponents();
        card=c;
        panelHolder = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tilbageKnap = new javax.swing.JButton();
        titelLabel = new javax.swing.JLabel();
        datoLabel = new javax.swing.JLabel();
        beskrivLabel = new javax.swing.JLabel();
        titelLabel3 = new javax.swing.JLabel();
        titelLabel4 = new javax.swing.JLabel();
        titelText = new javax.swing.JTextField();
        datoText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        titelLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        tilbageKnap.setBackground(new java.awt.Color(255, 255, 255));
        tilbageKnap.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        tilbageKnap.setText("Tilbage");
        tilbageKnap.setToolTipText("");
        tilbageKnap.setBorder(null);
        tilbageKnap.setBorderPainted(false);
        tilbageKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilbageKnapActionPerformed(evt);
            }
        });

        titelLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        titelLabel.setText("Titel:");

        datoLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        datoLabel.setText("Dato:");

        beskrivLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        beskrivLabel.setText("Beskrivelse:");

        titelLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        titelLabel3.setText("Kronisk:");

        titelLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        titelLabel4.setText("Behandler:");

        titelText.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        titelText.setText("IED");

        datoText.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        datoText.setText("14. maj 1980");
        datoText.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Intermittent explosive disorder");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField3.setText("Dr. Gert Gås");

        titelLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        titelLabel1.setText("Journal");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ja");

        jCheckBox2.setText("Nej");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titelLabel)
                    .addComponent(datoLabel)
                    .addComponent(beskrivLabel)
                    .addComponent(titelLabel4)
                    .addComponent(titelLabel3)
                    .addComponent(tilbageKnap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(titelLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                    .addComponent(datoText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titelText, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tilbageKnap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titelLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titelLabel)
                    .addComponent(titelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datoLabel)
                    .addComponent(datoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beskrivLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titelLabel3)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titelLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tilbageKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilbageKnapActionPerformed
        card.show(panelHolder, "patientPanel");
    }//GEN-LAST:event_tilbageKnapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beskrivLabel;
    private javax.swing.JLabel datoLabel;
    private javax.swing.JTextField datoText;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton tilbageKnap;
    private javax.swing.JLabel titelLabel;
    private javax.swing.JLabel titelLabel1;
    private javax.swing.JLabel titelLabel3;
    private javax.swing.JLabel titelLabel4;
    private javax.swing.JTextField titelText;
    // End of variables declaration//GEN-END:variables
}
