/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it3projekt;

import java.awt.CardLayout;
import javax.swing.*;

/**
 *
 * @author lenovo
 */
public class PatientPanel extends javax.swing.JPanel {
    private CardLayout card;
    private JPanel panelHolder;

    public PatientPanel(CardLayout c, JPanel p) {
        initComponents();
        card=c;
        panelHolder = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        tilbageKnap = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable3);

        setBackground(new java.awt.Color(255, 255, 255));

        tilbageKnap.setBackground(new java.awt.Color(255, 255, 255));
        tilbageKnap.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        tilbageKnap.setText("Tilbage");
        tilbageKnap.setToolTipText("");
        tilbageKnap.setBorder(null);
        tilbageKnap.setBorderPainted(false);
        tilbageKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilbageKnapActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Navn: ", "Anders And"},
                {"CPR:", "090634-2021"},
                {"Tlf. nr.:", "12345678"},
                {"Adresse:", "Gåsevænget 13"},
                {"Postnr. og by:", "1000 Andeby"}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(20);
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jTable2.setTableHeader(null);
        jScrollPane4.setViewportView(jTable2);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PTSD", "20/09-1945",  new Boolean(true), "Dr. Gert Gås"},
                {"IED", "14/05-1980",  new Boolean(true), "Dr. Gert Gås"},
                {"os femur faktur", "03/06-2010", null, "Dr. Gert Gås"}
            },
            new String [] {
                "Title", "Dato", "kronisk", "Behandler"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable4.setGridColor(new java.awt.Color(255, 255, 255));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tilbageKnap, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tilbageKnap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tilbageKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilbageKnapActionPerformed
        card.show(panelHolder, "kalenderPanel");
    }//GEN-LAST:event_tilbageKnapActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        card.show(panelHolder, "journalPanel");
    }//GEN-LAST:event_jTable4MouseClicked

    public void findPatient(String p){
        String patient=p; 
        System.out.println(patient);
       /* //denne kode virker i teorien, når arkiv
        arkiv.
        String navn = patient.substring(0, patient.indexOf("&")-1);
        patient = patient.substring(patient.indexOf("&")+1);
        String cpr=patient.substring(0, patient.indexOf("&")-1);
        patient = patient.substring(patient.indexOf("&")+1);
        String tlfnr=patient.substring(0, patient.indexOf("&")-1);
        patient = patient.substring(patient.indexOf("&")+1);
        String adresse= patient = patient.substring(0,patient.indexOf("&")-1);;
        patient = patient.substring(patient.indexOf("&")+1);
        String by= patient = patient.substring(0,patient.indexOf("&")-1);
        
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Navn: ", navn},
                {"CPR:", cpr},
                {"Tlf. nr.:", tlfnr},
                {"Adresse:", adresse},
                {"Postnr. og by:", by}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });*/
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton tilbageKnap;
    // End of variables declaration//GEN-END:variables
}
